### ISSUE TITLE
How to submit a PR?

### ISSUE THREAD

**Issue by yike21** [uestc-ndssl/training-plan#2]
# 提交PR需要注意的事项

## 基本操作流程

1. 从 [https://github.com/uestc-ndssl/training-plan](https://github.com/uestc-ndssl/training-plan) fork 到你自己的 github 中
2. 创建本地仓库：

   ```
   git clone https://github.com/ **YourGithubAccount** /training-plan
   cd training-plan
   ls

   git config user.name "???"
   git config user.email "???"

   git remote -v
   git remote add upstream https://github.com/uestc-ndssl/training-plan
   ```

3. 创建分支：

   ```
   git checkout -b **YourBranchName**
   ```

4. 从 https://github.com/uestc-ndssl/training-plan 获取最新更新，变基

   ```
   git fetch upstream
   git rebase upstream/master
   ```

5. 修改代码，之后提交代码：

   ```
   git status
   git add .
   git commit -s -m "feat: xxx"
   git push --set-upstream origin **YourBranchName**
   ```

6. 请求 review 代码的方法：在 github 网页上发起一个 PR（pull request）即可。

### 提交前
1. 建议本地仓库的master分支保持对上游的同步。

   ```
   # 在master分支下
   git pull
   ```

2. 建议基于最新的本地master分支创建新的分支

   ```
   # 在master分支下
   git pull
   git checkout -b **YourBranchName**
   ```

3. 提示，可基于最新的 master 进行 rebase

   ```
   # 在新创建的分支下，在你的最终提交后需要 rebase 最新的代码，若有冲突，需要处理冲突
   git rebase master
   ```

5. 要求一个 PR 对应一个 commit，同一分支下多次提交可采用 `--amend` 选项，或者在多次小的提交后进行 `squash` 。

   ```
   # 第二次提交时，采用追加方式
   git commit -s --amend 
   ```

### 提交后
1. 发起 PR 时，注意仔细填写 PR 信息，核对修改文件。
2. 提交后 **@ userID** 进行 review。

### GIT

[史上最浅显易懂的 Git 教程！ 廖雪峰](http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000)

[Pro Git（中文版）](http://git.oschina.net/progit/)

[撸袖子 动手学 Git 专治菜鸟](http://igit.linuxtoy.org/contents.html)

[Git 远程操作详解 阮一峰](http://www.ruanyifeng.com/blog/2014/06/git_remote.html)

[fork 后如何跟上源 repo 的变化](https://segmentfault.com/q/1010000002590371)

### Markdown

[Markdown 入门指南](http://www.jianshu.com/p/1e402922ee32)

**Comment by zhusl-2021** [comment]
Very useful.
